release:
  stage: build
  image: node:20.8.1-buster-slim
  only:
    - main
    - next
  script:
    - echo "@SDR:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm i -g semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/git @semantic-release/commit-analyzer conventional-changelog-conventionalcommits @semantic-release/npm
    - npx semantic-release --debug
